infra: making build fail while draft

diff --git a/azure-pipelines-validation.yml b/azure-pipelines-validation.yml
--- a/azure-pipelines-validation.yml
+++ b/azure-pipelines-validation.yml
@@ -31,7 +31,7 @@ pool: selfhosted-vmss-linux-lds-dev
 workspace:
   clean: all
 
-jobs: 
+jobs:
 - job: CheckForDraft
   displayName: Check for Draft Label
   steps:  
@@ -48,15 +48,14 @@ jobs:
           echo "$response" | jq '.[] | .name'
           echo "$response" | jq -e '.[] | select(.name == "draft")' > /dev/null
           if [ $? -eq 0 ]; then
-            echo "draft tag found"
-            echo "##vso[task.setvariable variable=skip;isOutput=true]true"
+            echo "draft label found - failing build - retrigger build after removing draft label"
+            exit 1
           else
             echo "draft tag not found"
             echo "##vso[task.setvariable variable=skip;isOutput=true]false"
           fi
 - job: BuildValidation
   dependsOn: CheckForDraft
-  condition: eq(dependencies.CheckForDraft.outputs['skip'], 'false')
   steps:
     - task: FileTransform@1
       displayName: "Transform AppSettings for CI"
